CREATE DATABASE bloggr;

CREATE TABLE articles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR (255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body LONGTEXT NOT NULL,
    creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);